# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ec66d6b1721deac76d4b81eed23c9133e8a607035627f5299c88736cf652f3c8120b9f0b9a6e4d71d4b5090a6fc3a63fe0b05d150fc99e6e65e8f9ada786830

test:
  secret_key_base: 2d3114e3285072981a1c5865ab46cc39e440e2962b3ce41da232f08fbc1f7796b437e26d003e02c1b44ab606580b30e887425c38d5fb8cd801447ce2636a168e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
